import { Command } from "commander";
import { existsSync, mkdirSync } from "fs";
import { log } from "../lib/logger.js";
import { handleError } from "../lib/errors.js";
import { getFont, getFontVariants } from "../lib/fonts-api.js";
import { toKotlinWeight } from "../lib/weights.js";

interface ThemeInitOpts {
  display?: string;
  headline?: string;
  body?: string;
  label?: string;
  output?: string;
  package?: string;
}

export const themeResource = new Command("theme")
  .description("Generate Material 3 theme files with custom fonts");

themeResource
  .command("init")
  .description("Initialize a Material 3 theme with font assignments")
  .option("--display <family>", "Font for display roles (default: Roboto)")
  .option("--headline <family>", "Font for headline roles (default: Roboto)")
  .option("--body <family>", "Font for body roles (default: Roboto)")
  .option("--label <family>", "Font for label roles (default: Roboto)")
  .option("-o, --output <dir>", "Output directory (default: ./theme)")
  .option("-p, --package <pkg>", "Kotlin package name")
  .addHelpText("after", [
    "",
    "Creates a complete Material 3 theme setup:",
    "  - Font.kt       – FontFamily declarations",
    "  - Type.kt       – Typography configuration",
    "  - Theme.kt      – MaterialTheme wrapper",
    "  - Color.kt      – Color scheme (placeholder)",
    "",
    "Examples:",
    "  font-m3-cli theme init",
    '  font-m3-cli theme init --display "Playfair Display" --body Inter',
    '  font-m3-cli theme init --output ./app/src/main/ui/theme -p com.myapp.theme',
  ].join("\n"))
  .action(async (opts: ThemeInitOpts) => {
    try {
      const display = opts.display ?? "Roboto";
      const headline = opts.headline ?? display;
      const body = opts.body ?? "Roboto";
      const label = opts.label ?? body;
      const pkg = opts.package ?? "";
      const outdir = opts.output ?? "theme";

      if (!existsSync(outdir)) {
        mkdirSync(outdir, { recursive: true });
      }

      const fontRoles: Record<string, string> = {
        display, headline, body, label,
      };

      const pkgPrefix = pkg ? `package ${pkg}\n\n` : "";
      const pkgStatement = pkg ? `package ${pkg}` : "// package name";

      const fontImports = `import androidx.compose.material3.Typography\nimport androidx.compose.ui.text.TextStyle\nimport androidx.compose.ui.text.font.Font\nimport androidx.compose.ui.text.font.FontFamily\nimport androidx.compose.ui.text.font.FontStyle\nimport androidx.compose.ui.text.font.FontWeight\nimport androidx.compose.ui.unit.sp`;

      const fontDeclarations: string[] = [];
      const uniqueFonts = [...new Set(Object.values(fontRoles))];

      for (const family of uniqueFonts) {
        const font = await getFont(family);
        if (!font) {
          log.warn(`Font "${family}" not found, skipping`);
          continue;
        }
        const variants = await getFontVariants(family);
        if (variants.length === 0) continue;

        const safeFamily = family.replace(/[^a-zA-Z0-9]/g, "_");
        const entries = variants.map((v) => {
          const fontWeight = toKotlinWeight(parseInt(v.weight));
          const style = v.italic ? ", FontStyle.Italic" : "";
          const filename = `${family.toLowerCase().replace(/ /g, "_")}_${v.weight}${v.italic ? "i" : ""}.ttf`;
          return `    Font(R.font.${filename.replace(/\.ttf$/, "")}, FontWeight.${fontWeight}${style})`;
        });

        fontDeclarations.push(`val ${safeFamily}FontFamily = FontFamily(\n${entries.join(",\n")}\n)`);
      }

      const fontFile = `${pkgPrefix}${fontImports}\n\n// Auto-generated by font-m3-cli\n\n${fontDeclarations.join("\n\n")}\n`;
      await Bun.write(`${outdir}/Font.kt`, fontFile);
      log.success(`  ${outdir}/Font.kt`);

      const typeScale: Record<string, { size: number; lineHeight: number; letterSpacing: string; weight: string }> = {
        displayLarge:    { size: 57, lineHeight: 64, letterSpacing: "(-0.25).sp", weight: "Bold" },
        displayMedium:   { size: 45, lineHeight: 52, letterSpacing: "0.sp",       weight: "Bold" },
        displaySmall:    { size: 36, lineHeight: 44, letterSpacing: "0.sp",       weight: "Bold" },
        headlineLarge:   { size: 32, lineHeight: 40, letterSpacing: "0.sp",       weight: "Bold" },
        headlineMedium:  { size: 28, lineHeight: 36, letterSpacing: "0.sp",       weight: "Medium" },
        headlineSmall:   { size: 24, lineHeight: 32, letterSpacing: "0.sp",       weight: "Medium" },
        titleLarge:      { size: 22, lineHeight: 28, letterSpacing: "0.sp",       weight: "Medium" },
        titleMedium:     { size: 16, lineHeight: 24, letterSpacing: "0.15.sp",    weight: "Medium" },
        titleSmall:      { size: 14, lineHeight: 20, letterSpacing: "0.1.sp",     weight: "Medium" },
        bodyLarge:       { size: 16, lineHeight: 24, letterSpacing: "0.5.sp",     weight: "Normal" },
        bodyMedium:      { size: 14, lineHeight: 20, letterSpacing: "0.25.sp",    weight: "Normal" },
        bodySmall:       { size: 12, lineHeight: 16, letterSpacing: "0.4.sp",     weight: "Normal" },
        labelLarge:      { size: 14, lineHeight: 20, letterSpacing: "0.1.sp",     weight: "Medium" },
        labelMedium:     { size: 12, lineHeight: 16, letterSpacing: "0.5.sp",     weight: "Medium" },
        labelSmall:      { size: 11, lineHeight: 16, letterSpacing: "0.5.sp",     weight: "Medium" },
      };

      const typeStyles: string[] = [];
      for (const [typoName, spec] of Object.entries(typeScale)) {
        const role = typoName.replace(/[A-Z].*$/, "").toLowerCase();
        const roleFont = fontRoles[role] ?? "Roboto";
        const safeRoleFont = roleFont.replace(/[^a-zA-Z0-9]/g, "_");

        typeStyles.push(`    ${typoName} = TextStyle(\n        fontFamily = ${safeRoleFont}FontFamily,\n        fontWeight = FontWeight.${spec.weight},\n        fontSize = ${spec.size}.sp,\n        lineHeight = ${spec.lineHeight}.sp,\n        letterSpacing = ${spec.letterSpacing},\n    )`);
      }

      const typeFile = `${pkgPrefix}${fontImports}\n\n// Auto-generated by font-m3-cli\n\nval AppTypography = Typography(\n${typeStyles.join(",\n\n")}\n)\n`;
      await Bun.write(`${outdir}/Type.kt`, typeFile);
      log.success(`  ${outdir}/Type.kt`);

      const themeFile = `${pkgPrefix}import androidx.compose.material3.MaterialTheme\nimport androidx.compose.material3.lightColorScheme\nimport androidx.compose.material3.darkColorScheme\nimport androidx.compose.runtime.Composable\n\n// Auto-generated by font-m3-cli\n\nprivate val LightColorScheme = lightColorScheme(\n    primary = md_theme_light_primary,\n    onPrimary = md_theme_light_onPrimary,\n    primaryContainer = md_theme_light_primaryContainer,\n    onPrimaryContainer = md_theme_light_onPrimaryContainer,\n    secondary = md_theme_light_secondary,\n    onSecondary = md_theme_light_onSecondary,\n    secondaryContainer = md_theme_light_secondaryContainer,\n    onSecondaryContainer = md_theme_light_onSecondaryContainer,\n    background = md_theme_light_background,\n    onBackground = md_theme_light_onBackground,\n    surface = md_theme_light_surface,\n    onSurface = md_theme_light_onSurface,\n)\n\nprivate val DarkColorScheme = darkColorScheme(\n    primary = md_theme_dark_primary,\n    onPrimary = md_theme_dark_onPrimary,\n    primaryContainer = md_theme_dark_primaryContainer,\n    onPrimaryContainer = md_theme_dark_onPrimaryContainer,\n    secondary = md_theme_dark_secondary,\n    onSecondary = md_theme_dark_onSecondary,\n    secondaryContainer = md_theme_dark_secondaryContainer,\n    onSecondaryContainer = md_theme_dark_onSecondaryContainer,\n    background = md_theme_dark_background,\n    onBackground = md_theme_dark_onBackground,\n    surface = md_theme_dark_surface,\n    onSurface = md_theme_dark_onSurface,\n)\n\n@Composable\nfun AppTheme(\n    darkTheme: Boolean = false,\n    content: @Composable () -> Unit\n) {\n    val colorScheme = if (darkTheme) DarkColorScheme else LightColorScheme\n\n    MaterialTheme(\n        colorScheme = colorScheme,\n        typography = AppTypography,\n        content = content\n    )\n}\n`;
      await Bun.write(`${outdir}/Theme.kt`, themeFile);
      log.success(`  ${outdir}/Theme.kt`);

      const colorFile = `${pkgStatement}\n\nimport androidx.compose.ui.graphics.Color\n\n// Auto-generated by font-m3-cli\n\nval md_theme_light_primary = Color(0xFF6750A4)\nval md_theme_light_onPrimary = Color(0xFFFFFFFF)\nval md_theme_light_primaryContainer = Color(0xFFEADDFF)\nval md_theme_light_onPrimaryContainer = Color(0xFF21005D)\nval md_theme_light_secondary = Color(0xFF625B71)\nval md_theme_light_onSecondary = Color(0xFFFFFFFF)\nval md_theme_light_secondaryContainer = Color(0xFFE8DEF8)\nval md_theme_light_onSecondaryContainer = Color(0xFF1D192B)\nval md_theme_light_background = Color(0xFFFFFBFE)\nval md_theme_light_onBackground = Color(0xFF1C1B1F)\nval md_theme_light_surface = Color(0xFFFFFBFE)\nval md_theme_light_onSurface = Color(0xFF1C1B1F)\n\nval md_theme_dark_primary = Color(0xFFD0BCFF)\nval md_theme_dark_onPrimary = Color(0xFF381E72)\nval md_theme_dark_primaryContainer = Color(0xFF4F378B)\nval md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)\nval md_theme_dark_secondary = Color(0xFFCCC2DC)\nval md_theme_dark_onSecondary = Color(0xFF332D41)\nval md_theme_dark_secondaryContainer = Color(0xFF4A4458)\nval md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)\nval md_theme_dark_background = Color(0xFF1C1B1F)\nval md_theme_dark_onBackground = Color(0xFFE6E1E5)\nval md_theme_dark_surface = Color(0xFF1C1B1F)\nval md_theme_dark_onSurface = Color(0xFFE6E1E5)\n`;
      await Bun.write(`${outdir}/Color.kt`, colorFile);
      log.success(`  ${outdir}/Color.kt`);

      log.success(`\nTheme initialized in ${outdir}/\n\nUsage:\n  Copy font .ttf files to app/src/main/res/font/\n  Use in your Activity: AppTheme { ... }\n`);
    } catch (err) {
      handleError(err);
    }
  });
