import { Command } from "commander";
import { existsSync, mkdirSync } from "fs";
import { log } from "../lib/logger.js";
import { handleError } from "../lib/errors.js";
import { getFont, getFontVariants, generateComposeCode } from "../lib/fonts-api.js";

interface ThemeInitOpts {
  display?: string;
  headline?: string;
  body?: string;
  label?: string;
  output?: string;
  package?: string;
}

export const themeResource = new Command("theme")
  .description("Generate Material 3 theme files with custom fonts");

themeResource
  .command("init")
  .description("Initialize a Material 3 theme with font assignments")
  .option("--display <family>", "Font for display roles (default: Roboto)")
  .option("--headline <family>", "Font for headline roles (default: Roboto)")
  .option("--body <family>", "Font for body roles (default: Roboto)")
  .option("--label <family>", "Font for label roles (default: Roboto)")
  .option("-o, --output <dir>", "Output directory (default: ./theme)")
  .option("-p, --package <pkg>", "Kotlin package name")
  .addHelpText("after", [
    "",
    "Creates a complete Material 3 theme setup:",
    "  - Font.kt       – FontFamily declarations",
    "  - Type.kt       – Typography configuration",
    "  - Theme.kt      – MaterialTheme wrapper",
    "  - Color.kt      – Color scheme (placeholder)",
    "",
    "Examples:",
    "  font-m3-cli theme init",
    '  font-m3-cli theme init --display "Playfair Display" --body Inter',
    '  font-m3-cli theme init --output ./app/src/main/ui/theme -p com.myapp.theme',
  ].join("\n"))
  .action(async (opts: ThemeInitOpts) => {
    try {
      const display = opts.display ?? "Roboto";
      const headline = opts.headline ?? display;
      const body = opts.body ?? "Roboto";
      const label = opts.label ?? body;
      const pkg = opts.package ?? "";
      const outdir = opts.output ?? "theme";

      if (!existsSync(outdir)) {
        mkdirSync(outdir, { recursive: true });
      }

      const fontRoles: Record<string, string> = {
        display, headline, body, label,
      };

      const pkgPrefix = pkg ? `package ${pkg}\n\n` : "";
      const pkgStatement = pkg ? `package ${pkg}` : "// package name";

      const fontImports = `import androidx.compose.material3.Typography\nimport androidx.compose.ui.text.TextStyle\nimport androidx.compose.ui.text.font.Font\nimport androidx.compose.ui.text.font.FontFamily\nimport androidx.compose.ui.text.font.FontStyle\nimport androidx.compose.ui.text.font.FontWeight\nimport androidx.compose.ui.unit.sp`;

      const fontDeclarations: string[] = [];
      const uniqueFonts = [...new Set(Object.values(fontRoles))];

      for (const family of uniqueFonts) {
        const font = await getFont(family);
        if (!font) {
          log.warn(`Font "${family}" not found, skipping`);
          continue;
        }
        const variants = await getFontVariants(family);
        if (variants.length === 0) continue;

        const safeFamily = family.replace(/[^a-zA-Z0-9]/g, "_");
        const entries = variants.map((v) => {
          const fontWeight = getWeightKotlin(parseInt(v.weight));
          const style = v.italic ? ", FontStyle.Italic" : "";
          const filename = `${family.toLowerCase().replace(/ /g, "_")}_${v.weight}${v.italic ? "i" : ""}.ttf`;
          return `    Font(R.font.${filename.replace(/\.ttf$/, "")}, FontWeight.${fontWeight}${style})`;
        });

        fontDeclarations.push(`val ${safeFamily}FontFamily = FontFamily(\n${entries.join(",\n")}\n)`);
      }

      const fontFile = `${pkgPrefix}${fontImports}\n\n// Auto-generated by font-m3-cli\n\n${fontDeclarations.join("\n\n")}\n`;
      await Bun.write(`${outdir}/Font.kt`, fontFile);
      log.success(`  ${outdir}/Font.kt`);

      const typoRoles = ["display", "headline", "title", "body", "label"];
      const sizes = ["Large", "Medium", "Small"];

      const typeStyles: string[] = [];
      for (const role of typoRoles) {
        const roleFont = fontRoles[role] ?? "Roboto";
        const safeRoleFont = roleFont.replace(/[^a-zA-Z0-9]/g, "_");
        for (const size of sizes) {
          const typoName = `${role}${size}`;
          const weight = role === "display" || role === "headline" ? "Bold" : role === "body" ? "Normal" : "Medium";
          const fs = role === "display" ? 57 - sizes.indexOf(size) * 12 : 32 - ["Large", "Medium", "Small"].indexOf(size) * 4 - typoRoles.indexOf(role) * 2;
          const lh = Math.round(fs * 1.2);
          const ls = typoName === "displayLarge" ? "(-0.25).sp" : typoName === "titleMedium" ? "0.15.sp" : typoName === "titleSmall" ? "0.1.sp" : typoName === "bodyLarge" ? "0.5.sp" : typoName === "bodyMedium" ? "0.25.sp" : typoName === "bodySmall" ? "0.4.sp" : typoName === "labelMedium" ? "0.5.sp" : typoName === "labelSmall" ? "0.5.sp" : typoName === "labelLarge" ? "0.1.sp" : "0.sp";

          typeStyles.push(`    ${typoName} = TextStyle(\n        fontFamily = ${safeRoleFont}FontFamily,\n        fontWeight = FontWeight.${weight},\n        fontSize = ${fs}.sp,\n        lineHeight = ${lh}.sp,\n        letterSpacing = ${ls},\n    )`);
        }
      }

      const typeFile = `${pkgPrefix}${fontImports}\n\n// Auto-generated by font-m3-cli\n\nval AppTypography = Typography(\n${typeStyles.join(",\n\n")}\n)\n`;
      await Bun.write(`${outdir}/Type.kt`, typeFile);
      log.success(`  ${outdir}/Type.kt`);

      const themeFile = `${pkgPrefix}import androidx.compose.material3.MaterialTheme\nimport androidx.compose.material3.lightColorScheme\nimport androidx.compose.material3.darkColorScheme\nimport androidx.compose.runtime.Composable\n\n// Auto-generated by font-m3-cli\n// Customize your colors in Color.kt\n\n@Composable\nfun AppTheme(\n    darkTheme: Boolean = false,\n    content: @Composable () -> Unit\n) {\n    val colorScheme = if (darkTheme) darkColorScheme() else lightColorScheme()\n\n    MaterialTheme(\n        colorScheme = colorScheme,\n        typography = AppTypography,\n        content = content\n    )\n}\n`;
      await Bun.write(`${outdir}/Theme.kt`, themeFile);
      log.success(`  ${outdir}/Theme.kt`);

      const colorFile = `${pkgStatement}\n\nimport androidx.compose.ui.graphics.Color\n\n// Auto-generated by font-m3-cli\n// Replace with your app's color palette\n\nval md_theme_light_primary = Color(0xFF6750A4)\nval md_theme_light_onPrimary = Color(0xFFFFFFFF)\nval md_theme_light_primaryContainer = Color(0xFFEADDFF)\nval md_theme_light_onPrimaryContainer = Color(0xFF21005D)\nval md_theme_light_secondary = Color(0xFF625B71)\nval md_theme_light_onSecondary = Color(0xFFFFFFFF)\nval md_theme_light_secondaryContainer = Color(0xFFE8DEF8)\nval md_theme_light_onSecondaryContainer = Color(0xFF1D192B)\nval md_theme_light_background = Color(0xFFFFFBFE)\nval md_theme_light_onBackground = Color(0xFF1C1B1F)\nval md_theme_light_surface = Color(0xFFFFFBFE)\nval md_theme_light_onSurface = Color(0xFF1C1B1F)\n\nval md_theme_dark_primary = Color(0xFFD0BCFF)\nval md_theme_dark_onPrimary = Color(0xFF381E72)\nval md_theme_dark_primaryContainer = Color(0xFF4F378B)\nval md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)\nval md_theme_dark_secondary = Color(0xFFCCC2DC)\nval md_theme_dark_onSecondary = Color(0xFF332D41)\nval md_theme_dark_secondaryContainer = Color(0xFF4A4458)\nval md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)\nval md_theme_dark_background = Color(0xFF1C1B1F)\nval md_theme_dark_onBackground = Color(0xFFE6E1E5)\nval md_theme_dark_surface = Color(0xFF1C1B1F)\nval md_theme_dark_onSurface = Color(0xFFE6E1E5)\n`;
      await Bun.write(`${outdir}/Color.kt`, colorFile);
      log.success(`  ${outdir}/Color.kt`);

      log.success(`\nTheme initialized in ${outdir}/\n\nUsage:\n  Copy font .ttf files to app/src/main/res/font/\n  Use in your Activity: AppTheme { ... }\n`);
    } catch (err) {
      handleError(err);
    }
  });

function getWeightKotlin(weight: number): string {
  if (weight <= 100) return "Thin";
  if (weight <= 200) return "ExtraLight";
  if (weight <= 300) return "Light";
  if (weight <= 400) return "Normal";
  if (weight <= 500) return "Medium";
  if (weight <= 600) return "SemiBold";
  if (weight <= 700) return "Bold";
  if (weight <= 800) return "ExtraBold";
  return "Black";
}
