import { describe, expect, test } from "bun:test";
import { toKotlinWeight, toLabel } from "../src/lib/weights.js";
import { generateCssCode, generateComposeCode } from "../src/lib/fonts-api.js";
import type { FontVariant } from "../src/lib/fonts-api.js";

// ── weights.ts ──────────────────────────────────────────

describe("toKotlinWeight", () => {
  const cases: [number, string][] = [
    [100, "Thin"],
    [200, "ExtraLight"],
    [300, "Light"],
    [400, "Normal"],
    [500, "Medium"],
    [600, "SemiBold"],
    [700, "Bold"],
    [800, "ExtraBold"],
    [900, "Black"],
  ];
  for (const [input, expected] of cases) {
    test(`${input} → ${expected}`, () => {
      expect(toKotlinWeight(input)).toBe(expected);
    });
  }

  test("edge: weight 0 defaults to Thin", () => {
    expect(toKotlinWeight(0)).toBe("Thin");
  });

  test("edge: weight 1000 defaults to Black", () => {
    expect(toKotlinWeight(1000)).toBe("Black");
  });
});

describe("toLabel", () => {
  test("400 → Regular (not Normal)", () => {
    expect(toLabel(400)).toBe("Regular");
  });

  test("700 → Bold", () => {
    expect(toLabel(700)).toBe("Bold");
  });
});

// ── fonts-api.ts Code Generation ──────────────────────

const sampleVariants: FontVariant[] = [
  { weight: "400", italic: false, url: "https://example.com/regular.ttf" },
  { weight: "700", italic: false, url: "https://example.com/bold.ttf" },
  { weight: "400", italic: true, url: "https://example.com/italic.ttf" },
];

describe("generateCssCode", () => {
  const css = generateCssCode("Roboto", sampleVariants);

  test("includes @font-face for each variant", () => {
    const count = (css.match(/@font-face/g) || []).length;
    expect(count).toBe(3);
  });

  test("contains font-family declaration", () => {
    expect(css).toContain("font-family: 'Roboto'");
  });

  test("contains font-weight values", () => {
    expect(css).toContain("font-weight: 400");
    expect(css).toContain("font-weight: 700");
  });

  test("includes italic style", () => {
    expect(css).toContain("font-style: italic");
  });

  test("includes CDN URLs", () => {
    expect(css).toContain("example.com");
  });

  test("generated banner comment", () => {
    expect(css).toContain("Generated by font-m3-cli");
  });
});

describe("generateComposeCode", () => {
  const code = generateComposeCode("Inter", sampleVariants, "com.myapp");

  test("includes package declaration", () => {
    expect(code).toContain("package com.myapp");
  });

  test("generates FontFamily with all variants", () => {
    expect(code).toContain("InterFontFamily = FontFamily(");
    expect(code).toContain("R.font.inter_400");
    expect(code).toContain("R.font.inter_700");
    expect(code).toContain("R.font.inter_400i");
  });

  test("uses FontWeight constants correctly", () => {
    expect(code).toContain("FontWeight.Normal");
    expect(code).toContain("FontWeight.Bold");
  });

  test("adds FontStyle.Italic for italic variants", () => {
    expect(code).toContain("FontStyle.Italic");
  });

  test("includes Material 3 Typography with all 15 roles", () => {
    for (const role of ["displayLarge", "displayMedium", "displaySmall", "headlineLarge", "headlineMedium", "headlineSmall", "titleLarge", "titleMedium", "titleSmall", "bodyLarge", "bodyMedium", "bodySmall", "labelLarge", "labelMedium", "labelSmall"]) {
      expect(code).toContain(role);
    }
  });

  test("has correct font sizes per M3 spec", () => {
    expect(code).toContain("fontSize = 57.sp");
    expect(code).toContain("fontSize = 16.sp");
    expect(code).toContain("fontSize = 11.sp");
  });
});

describe("generateComposeCode without package", () => {
  const code = generateComposeCode("Inter", sampleVariants);

  test("does not include package line", () => {
    expect(code).not.toContain("package ");
  });

  test("generated banner comment with date", () => {
    expect(code).toContain("Generated by font-m3-cli");
    expect(code).toContain("Font: Inter");
  });
});
